HAWQ-1540. PXF should not accept parameters for init command

diff --git a/pxf/pxf-service/src/scripts/pxf-service b/pxf/pxf-service/src/scripts/pxf-service
--- a/pxf/pxf-service/src/scripts/pxf-service
+++ b/pxf/pxf-service/src/scripts/pxf-service
@@ -57,6 +57,13 @@ fi
 
 curl=`which curl`
 
+# print error message and return with error code
+function fail()
+{
+    echo "ERROR: $1"
+    exit 1
+}
+
 #
 # createInstance creates a tomcat instance 
 # configuration files 
@@ -206,24 +213,13 @@ function doInit()
 		echo WARNING: instance already exists in $instance_root, nothing to do...
 		return 0
 	fi
-	# Generate private classpath file only if user specified hadoop_home option
-	# Otherwise use default file
-    if [ ! -z $hadoop_home ]; then
-        generatePrivateClasspath || return 1
-    else
-        if [ ! -z $hbase_home ]; then
-            echo WARNING: hbase_home option will be ignored, please specify hadoop_home
-        fi
-        if [ ! -z $hive_home ]; then
-            echo WARNING: hive_home option will be ignored, please specify hadoop_home
-        fi
-    fi
+	determineHadoopDistro
+	generatePrivateClasspath || return 1
 	createInstance || return 1
 	configureInstance || return 1
 	deployWebapp || return 1
 	createLogsDir || return 1
 	createRunDir  || return 1
-
 }
 
 #
@@ -292,38 +288,90 @@ function createRunDir()
     return 0
 }
 
+function check_hadoop_install()
+{
+    local distro_type=${1}
+    case "${distro_type}" in
+        hdp|HDP)
+            if [ -d "/usr/hdp/current/hadoop-client/client" ]; then
+                DISTRO="hdp"
+                return 0;
+            fi
+            ;;
+        cdh|CDH)
+            if [ -d "/usr/lib/hadoop/client" ]; then
+                DISTRO="cdh"
+                return 0;
+            fi
+            ;;
+        tar|TAR)
+            if [ -n "${HADOOP_ROOT}" ] && [ -d "${HADOOP_ROOT}/hadoop/share/hadoop/common/lib" ]; then
+                DISTRO="tar"
+                return 0;
+            fi
+            ;;
+        custom|CUSTOM)
+            # use tarball template for custom distro, do not require HADOOP_ROOT to be set
+            DISTRO="tar"
+            return 0;
+            ;;
+        *)
+            fail "Unknown hadoop distribution type: HADOOP_DISTRO=${distro_type}"
+            ;;
+    esac
+    # the distro type was not found installed, return failure code
+    return 1
+}
+
+function determineHadoopDistro()
+{
+    DISTRO=""
+    # check if the distro is explicitly specified
+    if [ -z "${HADOOP_DISTRO}" ]; then
+        # if distro is not specified, try checking for HDP and then CDH
+        check_hadoop_install "hdp" || check_hadoop_install "cdh"
+    else
+        # check distro specified in the config file
+        check_hadoop_install "${HADOOP_DISTRO}"
+    fi
+
+    # if still not determined, check tarball-based install
+    if [ -z "${DISTRO}" ]; then
+        check_hadoop_install "tar"
+        # if still unknown, then error out
+        if [ -z "${DISTRO}" ]; then
+            fail "Can not determine Hadoop distribution, please install Hadoop clients."
+        fi
+    fi
+}
+
 function generatePrivateClasspath()
 {
-    echo "Generating private classpath file..."
-    #Create intial version of the file
-    sed -e "s|PXF_HOME|$PXF_HOME|g" $PXF_HOME/conf-templates/pxf-private.classpath.template > $PXF_HOME/conf/pxf-private.classpath
-    #Make sure $hadoop_home is defined
-    if [ -z $hadoop_home ]; then
-        echo ERROR: cant generate private classpath without hadoop_home value
-        return 1
+    # distro must have been determined by now, but double check
+    if [ -z "${DISTRO}" ]; then
+        fail "Hadoop distribution was not determined"
     fi
-    #Substitute HADOOP_HOME value
-    sed -i -e "s|HADOOP_HOME|$hadoop_home|g" $PXF_HOME/conf/pxf-private.classpath
-    if [ ! -z $hbase_home ]; then
-        #Substitute HBASE_HOME if hbase_home was set
-        sed -i -e "s|HBASE_HOME|$hbase_home|g" $PXF_HOME/conf/pxf-private.classpath
-    else
-        #Delete lines with HBASE_HOME if hbase_home wasn't set
-        sed -i -e "/HBASE_HOME/d" $PXF_HOME/conf/pxf-private.classpath
+
+    # verify that a template file for the distribution exists
+    local template_file="${PXF_HOME}/conf-templates/pxf-private-${DISTRO}.classpath.template"
+    if [ ! -f "${template_file}" ]; then
+        fail "Template file ${template_file} not found"
     fi
-    if [ ! -z $hive_home ]; then
-        #Substitute HIVE_HOME if hive_home was set
-        sed -i -e "s|HIVE_HOME|$hive_home|g" $PXF_HOME/conf/pxf-private.classpath
-    else
-        #Delete lines with HIVE_HOME if hive_home wasn't set
-        sed -i -e "/HIVE_HOME/d" $PXF_HOME/conf/pxf-private.classpath
+
+    echo "Generating ${PXF_HOME}/conf/pxf-private.classpath file from ${template_file} ..."
+
+    # create initial version of the file by replacing PXF_HOME token (applicable to all templates)
+    sed -e "s|PXF_HOME|${PXF_HOME}|g" ${template_file} > ${PXF_HOME}/conf/pxf-private.classpath
+
+    # substitute HADOOP_ROOT value if defined
+    if [ -n "${HADOOP_ROOT}" ]; then
+        sed -i -e "s|HADOOP_ROOT|${HADOOP_ROOT}|g" ${PXF_HOME}/conf/pxf-private.classpath
     fi
 }
 
 function printUsage()
 {
-    echo $"Usage: $0 {start|stop|restart|init --hadoop-home HADOOP_LOCATION [--hive-home HIVE_LOCATION --hbase-home HBASE_LOCATION]|status}"
-
+    echo $"Usage: $0 {start|stop|restart|init|status}"
 }
 
 function validateParameters()
@@ -360,8 +408,6 @@ function validateParameters()
         echo "ERROR: Cannot run as root user"
         exit 1
     fi
-
-
 
     # validate JAVA_HOME
     if [ ! -x $JAVA_HOME/bin/java ]; then
@@ -415,31 +461,6 @@ command=$1
 
 case "$command" in
 	"init" )
-		shift
-		while [[ $# -gt 1 ]]
-		do
-			name="$1"
-			value="$2"
-			case $name in
-				--hadoop-home)
-				hadoop_home="$2"
-				shift
-				;;
-				--hive-home)
-                                hive_home="$2"
-                                shift
-                                ;;
-				--hbase-home)
-                                hbase_home="$2"
-                                shift
-                                ;;
-				*)
-                                echo "$name is an unknown option"
-                                printUsage
-                                exit 1
-			esac
-			shift
-		done
 		validateParameters
 		doInit
 		;;
