HAWQ-1534. Change user to PXF_USER only for HAWQ database.

diff --git a/pxf/pxf-service/src/scripts/pxf-service b/pxf/pxf-service/src/scripts/pxf-service
--- a/pxf/pxf-service/src/scripts/pxf-service
+++ b/pxf/pxf-service/src/scripts/pxf-service
@@ -35,7 +35,7 @@ else
 	source $env_script
 fi
 
-pxf_user=${PXF_USER:-pxf}
+pxf_user=${PXF_USER}
 instance_port=${PXF_PORT:-51200}
 instance_name=pxf-service
 
@@ -72,9 +72,11 @@ function createInstance()
 		return 1
 	fi
 
-	chown -R $instance_owner $instance_root
-	chmod 700 $instance_root/$instance_name
-	return 0
+    if [ ! -z $pxf_user ]; then
+        chown -R $instance_owner $instance_root
+    fi
+    chmod 700 $instance_root/$instance_name
+    return 0
 }
 
 #
@@ -257,7 +259,13 @@ function commandWebapp()
 {
     command=$1
     pushd $instance_root
-    sudo -u $pxf_user $instance_root/$instance_name/bin/catalina.sh $command
+    if [ ! -z $pxf_user ]; then
+        # Run command as a pxf_user
+        su $pxf_user -c "$instance_root/$instance_name/bin/catalina.sh $command"
+    else
+        # Run command as a current user
+        $instance_root/$instance_name/bin/catalina.sh $command
+    fi
     if [ $? -ne 0 ]; then
         return 1
     fi
@@ -267,7 +275,9 @@ function commandWebapp()
 function createLogsDir()
 {
     mkdir -p $PXF_LOGDIR
-    chown -R $instance_owner $PXF_LOGDIR
+    if [ ! -z $pxf_user ]; then
+        chown -R $instance_owner $PXF_LOGDIR
+    fi
     chmod 700 $PXF_LOGDIR
     return 0
 }
@@ -275,7 +285,9 @@ function createLogsDir()
 function createRunDir()
 {
     mkdir -p $PXF_RUNDIR
-    chown -R $instance_owner $PXF_RUNDIR
+    if [ ! -z $pxf_user ]; then
+        chown -R $instance_owner $PXF_RUNDIR
+    fi
     chmod 700 $PXF_RUNDIR
     return 0
 }
@@ -297,14 +309,14 @@ function generatePrivateClasspath()
         sed -i -e "s|HBASE_HOME|$hbase_home|g" $PXF_HOME/conf/pxf-private.classpath
     else
         #Delete lines with HBASE_HOME if hbase_home wasn't set
-        sed -i  "/HBASE_HOME/d" $PXF_HOME/conf/pxf-private.classpath
+        sed -i -e "/HBASE_HOME/d" $PXF_HOME/conf/pxf-private.classpath
     fi
     if [ ! -z $hive_home ]; then
         #Substitute HIVE_HOME if hive_home was set
         sed -i -e "s|HIVE_HOME|$hive_home|g" $PXF_HOME/conf/pxf-private.classpath
     else
         #Delete lines with HIVE_HOME if hive_home wasn't set
-        sed -i  "/HIVE_HOME/d" $PXF_HOME/conf/pxf-private.classpath
+        sed -i -e "/HIVE_HOME/d" $PXF_HOME/conf/pxf-private.classpath
     fi
 }
 
@@ -334,12 +346,22 @@ function validateParameters()
     fi
 
     # validate pxf user
-    id $pxf_user  &> /dev/null;
-    if [ "$?" -ne "0" ]
-    then
-        echo "ERROR: User $pxf_user doesn't exist. Please set valid user via \$PXF_USER variable"
+    if [ ! -z $pxf_user ]; then
+        id $pxf_user  &> /dev/null;
+        if [ "$?" -ne "0" ]
+        then
+            echo "ERROR: User $pxf_user doesn't exist. Please set valid user via \$PXF_USER variable"
+            exit 1
+        fi
+    fi
+
+    # make sure current user is not root
+    if [ $EUID -eq 0 ]; then
+        echo "ERROR: Cannot run as root user"
         exit 1
     fi
+
+
 
     # validate JAVA_HOME
     if [ ! -x $JAVA_HOME/bin/java ]; then
